sudo: false
dist: trusty
language: cpp

cache: 
  - apt: true
  - ccache
  
git:
  submodules: false

notifications:
  slack: dicl:WvBJLVrHw7j1IaIZun64ncjE

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest

    packages:
      - libboost1.55-all-dev
      - build-essential
      - gcc-4.9
      - g++-4.9
      - libunittest++-dev
      - python2.7-dev
      - gdb 
      - libzookeeper-mt-dev

before_script:
  - export CXX=g++-4.9
  - mkdir build

script: 
  - sh autogen.sh
  - cd build
  - export LIBRARY_PATH=`pwd`/lib
  - export LD_LIBRARY_PATH=`pwd`/lib
  - LIBRARY_PATH=`pwd`/lib sh ../configure --prefix=`pwd`
  - make -j4 install
  - make -j4 check
